### ISSUE TITLE
Python script can't detect discord when start as a linux service

### ISSUE THREAD

**Issue by ndak0ta** [zorua98741/PS3-Rich-Presence-for-Discord#6]
It works when i run script from terminal but i wanted to make it a service so it will automatically run on startup 
![image](https://user-images.githubusercontent.com/37935304/190853605-35c7c5ed-5573-4126-9123-16281298950e.png)
my service file:
![image](https://user-images.githubusercontent.com/37935304/190853664-e2f71cdf-657b-450f-ac6f-512d17500414.png)

**Comment by zorua98741** [comment]
Hi, looking at the error code I assume it is because Discord has not completed its start-up procedures before PS3RPD attempts to connect (and likely the "findDiscord()" function is broken on Linux)
I've got a Ubuntu virtual machine set up to test on, but I may not have time to test and implement potential fixes until the 23rd of September.
